# Hyperparameter Tuning using Keras

In this notebook, we learn how to tune a set of hyperparameters for an Artificial Neural Network (ANN) using Keras.

ANNs are highly flexible. This comes with a cost. There could be many hyperparameters to tune. Eevn in simple Multi-Layer Perceptron (MLP) we can change the number of hidden layers, neurons, type of activation functions, weight initializer, regularizers, etc.

We can perform K-fold cross-validation by using Scikit-Learn's GridSearchCV or RandomizedSearchCV. To do this, we need to wrap our Keras models in objects that mimic regular Scikit-Learn classifiers or regressors. The first step is to create a function that will build and compile a Keras model, given a set of hyperparameters (that we wish to tune)

We conduct a simple illustrative experiment to tune two hyperparameters for a fixed architecture MLP on the MNIST handwritten digits dataset: learning rate and momentum for the SGD (Stochastic Gradient Descent) optimizer

In [1]:
import warnings
import os
import time
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, cross_val_predict


import tensorflow as tf
from tensorflow import keras

## Load the Dataset

We load the dataset using Keras. Then, create train, test and validation subset. Finally, scale the data.

In [2]:
mnist = keras.datasets.mnist

(X_train_full, y_train_full), (X_test, y_test) = mnist.load_data()


X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]
X_test = X_test / 255.0

print("No. of Training Samples: ", X_train.shape)
print("No. of Training Labels: ", y_train.shape)

print("\nNo. of Validation Samples: ", X_valid.shape)
print("No. of Validation Labels: ", y_valid.shape)

print("\nNo. of Testing Samples: ", X_test.shape)
print("No. of Testing Labels: ", y_test.shape)

print("\nX type: ", X_train.dtype)
print("y type: ", y_train.dtype)

No. of Training Samples:  (55000, 28, 28)
No. of Training Labels:  (55000,)

No. of Validation Samples:  (5000, 28, 28)
No. of Validation Labels:  (5000,)

No. of Testing Samples:  (10000, 28, 28)
No. of Testing Labels:  (10000,)

X type:  float64
y type:  uint8


## A function to Build and Compile a Keras Model

Note that we use only two hyperparameters as arguments of the function that we want to tune.

It is good practice to provide reasonable defaults to the hyperparameters, as Scikit-Learn does.

In [3]:
def build_model(sgd_lrate=3e-3, sgd_momentum=0.1):
    
    model = keras.models.Sequential()
    model.add(keras.layers.Flatten(input_shape=[28, 28]))
    model.add(keras.layers.Dense(300, activation="relu"))
    model.add(keras.layers.Dense(100, activation="relu"))
    model.add(keras.layers.Dense(10, activation="softmax"))
    
    optimizer = keras.optimizers.SGD(learning_rate=sgd_lrate, momentum=sgd_momentum)
    
    model.compile(loss="sparse_categorical_crossentropy",
                  optimizer=optimizer,
                  metrics=["accuracy"])
    
    return model

## Implementation of the Scikit-Learn Classifier API for Keras

We create a KerasClassifier object. It is a thin wrapper around the Keras model built using build_model(). 

It will use the default hyperparameters we defined in build_model(). 

We can use this object like a regular Scikit-Learn classifier.

In [4]:
keras_classifier = tf.keras.wrappers.scikit_learn.KerasClassifier(build_model)

## Hyperparameter Tuning

For hyperparameter tuning we create a GridSearchCV object using the KerasClassifier and a set of hyperparameters with their list of values.

In the fit() method of the GridSearchCV object we pass some parameters for the underlying Keras model. 

Since the GridSearchCV uses K-fold cross-validation, it does not use X_valid and y_valid in the argument of the fit() method. Those are only used for early stopping.

In [5]:
%%time

warnings.filterwarnings('ignore')

# The param_grid tells Scikit-Learn to evaluate all combinations of the hyperparameter values
param_grid = {'sgd_lrate': [1e-2, 1e-1, 2e-1], 
              'sgd_momentum': [0.1, 0.3, 0.5]}


early_stopping_cb = keras.callbacks.EarlyStopping(monitor='val_loss',
                                  min_delta=0, 
                                  patience=10, 
                                  verbose=0, 
                                  mode='auto',
                                  restore_best_weights=True)

mlp_cv = GridSearchCV(keras_classifier, param_grid, scoring='accuracy', cv=5, verbose=1)
mlp_cv.fit(X_train, y_train, 
           epochs=100,
           validation_data=(X_valid, y_valid),
           callbacks=[early_stopping_cb])


params_optimal_mlp = mlp_cv.best_params_

print("Best Score: %f" % mlp_cv.best_score_)
print("Optimal Hyperparameter Values: ", params_optimal_mlp)
print("\n")

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Train on 44000 samples, validate on 5000 samples
Epoch 1/100
44000/44000 [==============================] - 3s 77us/sample - loss: 0.6326 - accuracy: 0.8376 - val_loss: 0.3262 - val_accuracy: 0.9126
Epoch 2/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.2993 - accuracy: 0.9147 - val_loss: 0.2533 - val_accuracy: 0.9314
Epoch 3/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.2450 - accuracy: 0.9311 - val_loss: 0.2165 - val_accuracy: 0.9398
Epoch 4/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.2116 - accuracy: 0.9407 - val_loss: 0.1961 - val_accuracy: 0.9452
Epoch 5/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.1861 - accuracy: 0.9475 - val_loss: 0.1744 - val_accuracy: 0.9514
Epoch 6/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.1665 - accuracy: 0.9532 - val_loss: 0.1589 - val_accuracy: 0.9556
Epoch 7/100
44000/44000 [==========================

Epoch 55/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0086 - accuracy: 0.9993 - val_loss: 0.0747 - val_accuracy: 0.9790
Epoch 56/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0082 - accuracy: 0.9993 - val_loss: 0.0753 - val_accuracy: 0.9786
Epoch 57/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0078 - accuracy: 0.9995 - val_loss: 0.0733 - val_accuracy: 0.9794
Train on 44000 samples, validate on 5000 samples
Epoch 1/100
44000/44000 [==============================] - 3s 75us/sample - loss: 0.6382 - accuracy: 0.8320 - val_loss: 0.3170 - val_accuracy: 0.9166
Epoch 2/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.3008 - accuracy: 0.9140 - val_loss: 0.2532 - val_accuracy: 0.9302
Epoch 3/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.2459 - accuracy: 0.9286 - val_loss: 0.2114 - val_accuracy: 0.9438
Epoch 4/100
44000/44000 [=======================

Epoch 3/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.2467 - accuracy: 0.9295 - val_loss: 0.2219 - val_accuracy: 0.9394
Epoch 4/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.2113 - accuracy: 0.9405 - val_loss: 0.1907 - val_accuracy: 0.9474
Epoch 5/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.1860 - accuracy: 0.9467 - val_loss: 0.1723 - val_accuracy: 0.9518
Epoch 6/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.1650 - accuracy: 0.9522 - val_loss: 0.1620 - val_accuracy: 0.9558
Epoch 7/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.1486 - accuracy: 0.9579 - val_loss: 0.1452 - val_accuracy: 0.9608
Epoch 8/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.1346 - accuracy: 0.9622 - val_loss: 0.1360 - val_accuracy: 0.9644
Epoch 9/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.1229 - accuracy:

44000/44000 [==============================] - 3s 65us/sample - loss: 0.0943 - accuracy: 0.9732 - val_loss: 0.1140 - val_accuracy: 0.9684
Epoch 13/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0872 - accuracy: 0.9759 - val_loss: 0.1062 - val_accuracy: 0.9710
Epoch 14/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0805 - accuracy: 0.9779 - val_loss: 0.1028 - val_accuracy: 0.9716
Epoch 15/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0750 - accuracy: 0.9793 - val_loss: 0.0998 - val_accuracy: 0.9722
Epoch 16/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0698 - accuracy: 0.9811 - val_loss: 0.0960 - val_accuracy: 0.9732
Epoch 17/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0650 - accuracy: 0.9828 - val_loss: 0.0980 - val_accuracy: 0.9718
Epoch 18/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0612 - accuracy: 0.983

44000/44000 [==============================] - 3s 63us/sample - loss: 0.0487 - accuracy: 0.9875 - val_loss: 0.0800 - val_accuracy: 0.9762
Epoch 22/100
44000/44000 [==============================] - 3s 63us/sample - loss: 0.0458 - accuracy: 0.9886 - val_loss: 0.0804 - val_accuracy: 0.9742
Epoch 23/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0428 - accuracy: 0.9899 - val_loss: 0.0773 - val_accuracy: 0.9758
Epoch 24/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0401 - accuracy: 0.9901 - val_loss: 0.0797 - val_accuracy: 0.9750
Epoch 25/100
44000/44000 [==============================] - 3s 69us/sample - loss: 0.0375 - accuracy: 0.9911 - val_loss: 0.0769 - val_accuracy: 0.9762
Epoch 26/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0352 - accuracy: 0.9920 - val_loss: 0.0765 - val_accuracy: 0.9768
Epoch 27/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0334 - accuracy: 0.992

44000/44000 [==============================] - 3s 65us/sample - loss: 0.0251 - accuracy: 0.9950 - val_loss: 0.0757 - val_accuracy: 0.9780
Epoch 27/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0234 - accuracy: 0.9956 - val_loss: 0.0772 - val_accuracy: 0.9772
Epoch 28/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0216 - accuracy: 0.9957 - val_loss: 0.0775 - val_accuracy: 0.9778
Epoch 29/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0201 - accuracy: 0.9966 - val_loss: 0.0738 - val_accuracy: 0.9782
Epoch 30/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0186 - accuracy: 0.9970 - val_loss: 0.0760 - val_accuracy: 0.9762
Epoch 31/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0174 - accuracy: 0.9972 - val_loss: 0.0760 - val_accuracy: 0.9782
Epoch 32/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0160 - accuracy: 0.997

44000/44000 [==============================] - 3s 64us/sample - loss: 0.0084 - accuracy: 0.9995 - val_loss: 0.0730 - val_accuracy: 0.9788
Epoch 42/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0081 - accuracy: 0.9995 - val_loss: 0.0721 - val_accuracy: 0.9794
Epoch 43/100
44000/44000 [==============================] - 3s 68us/sample - loss: 0.0076 - accuracy: 0.9996 - val_loss: 0.0734 - val_accuracy: 0.9788
Train on 44000 samples, validate on 5000 samples
Epoch 1/100
44000/44000 [==============================] - 3s 76us/sample - loss: 0.5725 - accuracy: 0.8487 - val_loss: 0.2936 - val_accuracy: 0.9218
Epoch 2/100
44000/44000 [==============================] - 3s 70us/sample - loss: 0.2726 - accuracy: 0.9225 - val_loss: 0.2340 - val_accuracy: 0.9374
Epoch 3/100
44000/44000 [==============================] - 3s 68us/sample - loss: 0.2199 - accuracy: 0.9379 - val_loss: 0.1941 - val_accuracy: 0.9480
Epoch 4/100
44000/44000 [==============================] - 3s

Epoch 10/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0929 - accuracy: 0.9742 - val_loss: 0.1049 - val_accuracy: 0.9700
Epoch 11/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0843 - accuracy: 0.9766 - val_loss: 0.1033 - val_accuracy: 0.9702
Epoch 12/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0770 - accuracy: 0.9787 - val_loss: 0.0954 - val_accuracy: 0.9724
Epoch 13/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0705 - accuracy: 0.9805 - val_loss: 0.0932 - val_accuracy: 0.9724
Epoch 14/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0646 - accuracy: 0.9827 - val_loss: 0.0906 - val_accuracy: 0.9732
Epoch 15/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0594 - accuracy: 0.9839 - val_loss: 0.0897 - val_accuracy: 0.9748
Epoch 16/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0548 - ac

Epoch 26/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0238 - accuracy: 0.9953 - val_loss: 0.0727 - val_accuracy: 0.9768
Epoch 27/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0218 - accuracy: 0.9962 - val_loss: 0.0769 - val_accuracy: 0.9754
Epoch 28/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0203 - accuracy: 0.9962 - val_loss: 0.0734 - val_accuracy: 0.9788
Epoch 29/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0189 - accuracy: 0.9965 - val_loss: 0.0759 - val_accuracy: 0.9764
Epoch 30/100
44000/44000 [==============================] - 3s 68us/sample - loss: 0.0176 - accuracy: 0.9971 - val_loss: 0.0746 - val_accuracy: 0.9778
Epoch 31/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0163 - accuracy: 0.9975 - val_loss: 0.0768 - val_accuracy: 0.9764
Epoch 32/100
44000/44000 [==============================] - 3s 63us/sample - loss: 0.0152 - ac

Epoch 7/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0978 - accuracy: 0.9725 - val_loss: 0.1038 - val_accuracy: 0.9700
Epoch 8/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0854 - accuracy: 0.9756 - val_loss: 0.1006 - val_accuracy: 0.9724
Epoch 9/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0749 - accuracy: 0.9791 - val_loss: 0.0911 - val_accuracy: 0.9732
Epoch 10/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0668 - accuracy: 0.9813 - val_loss: 0.0880 - val_accuracy: 0.9754
Epoch 11/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0596 - accuracy: 0.9831 - val_loss: 0.0821 - val_accuracy: 0.9776
Epoch 12/100
44000/44000 [==============================] - 3s 73us/sample - loss: 0.0530 - accuracy: 0.9855 - val_loss: 0.0820 - val_accuracy: 0.9766
Epoch 13/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0474 - accur

44000/44000 [==============================] - 3s 67us/sample - loss: 0.0098 - accuracy: 0.9991 - val_loss: 0.0680 - val_accuracy: 0.9796
Epoch 29/100
44000/44000 [==============================] - 3s 66us/sample - loss: 0.0089 - accuracy: 0.9993 - val_loss: 0.0690 - val_accuracy: 0.9792
Epoch 30/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0080 - accuracy: 0.9995 - val_loss: 0.0704 - val_accuracy: 0.9792
Epoch 31/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0075 - accuracy: 0.9995 - val_loss: 0.0705 - val_accuracy: 0.9798
Epoch 32/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0069 - accuracy: 0.9996 - val_loss: 0.0692 - val_accuracy: 0.9804
Epoch 33/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0065 - accuracy: 0.9998 - val_loss: 0.0691 - val_accuracy: 0.9802
Epoch 34/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0060 - accuracy: 0.999

Epoch 9/100
44000/44000 [==============================] - 3s 70us/sample - loss: 0.0753 - accuracy: 0.9790 - val_loss: 0.0966 - val_accuracy: 0.9724
Epoch 10/100
44000/44000 [==============================] - 3s 71us/sample - loss: 0.0669 - accuracy: 0.9818 - val_loss: 0.0949 - val_accuracy: 0.9716
Epoch 11/100
44000/44000 [==============================] - 3s 68us/sample - loss: 0.0596 - accuracy: 0.9835 - val_loss: 0.0855 - val_accuracy: 0.9726
Epoch 12/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0532 - accuracy: 0.9855 - val_loss: 0.0829 - val_accuracy: 0.9746
Epoch 13/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0478 - accuracy: 0.9868 - val_loss: 0.0829 - val_accuracy: 0.9760
Epoch 14/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0424 - accuracy: 0.9888 - val_loss: 0.0806 - val_accuracy: 0.9746
Epoch 15/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0383 - acc

44000/44000 [==============================] - 3s 64us/sample - loss: 0.0011 - accuracy: 1.0000 - val_loss: 0.0722 - val_accuracy: 0.9824
Epoch 16/100
44000/44000 [==============================] - 3s 65us/sample - loss: 8.7836e-04 - accuracy: 1.0000 - val_loss: 0.0743 - val_accuracy: 0.9838
Epoch 17/100
44000/44000 [==============================] - 3s 64us/sample - loss: 7.6654e-04 - accuracy: 1.0000 - val_loss: 0.0746 - val_accuracy: 0.9832
Epoch 18/100
44000/44000 [==============================] - 3s 64us/sample - loss: 6.7847e-04 - accuracy: 1.0000 - val_loss: 0.0746 - val_accuracy: 0.9828
Epoch 19/100
44000/44000 [==============================] - 3s 64us/sample - loss: 6.0942e-04 - accuracy: 1.0000 - val_loss: 0.0749 - val_accuracy: 0.9832
Train on 44000 samples, validate on 5000 samples
Epoch 1/100
44000/44000 [==============================] - 4s 80us/sample - loss: 0.2711 - accuracy: 0.9184 - val_loss: 0.1356 - val_accuracy: 0.9598
Epoch 2/100
44000/44000 [==================

Epoch 5/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0354 - accuracy: 0.9884 - val_loss: 0.0795 - val_accuracy: 0.9776
Epoch 6/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0262 - accuracy: 0.9916 - val_loss: 0.0765 - val_accuracy: 0.9794
Epoch 7/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0193 - accuracy: 0.9939 - val_loss: 0.0773 - val_accuracy: 0.9792
Epoch 8/100
44000/44000 [==============================] - 3s 67us/sample - loss: 0.0156 - accuracy: 0.9948 - val_loss: 0.0787 - val_accuracy: 0.9802
Epoch 9/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0098 - accuracy: 0.9971 - val_loss: 0.0959 - val_accuracy: 0.9770
Epoch 10/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0073 - accuracy: 0.9980 - val_loss: 0.0791 - val_accuracy: 0.9828
Epoch 11/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0039 - accurac

Epoch 3/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0663 - accuracy: 0.9793 - val_loss: 0.0870 - val_accuracy: 0.9746
Epoch 4/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0476 - accuracy: 0.9847 - val_loss: 0.0762 - val_accuracy: 0.9800
Epoch 5/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0321 - accuracy: 0.9893 - val_loss: 0.0844 - val_accuracy: 0.9794
Epoch 6/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0270 - accuracy: 0.9910 - val_loss: 0.0744 - val_accuracy: 0.9798
Epoch 7/100
44000/44000 [==============================] - 3s 65us/sample - loss: 0.0202 - accuracy: 0.9936 - val_loss: 0.0762 - val_accuracy: 0.9802
Epoch 8/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0107 - accuracy: 0.9966 - val_loss: 0.0737 - val_accuracy: 0.9820
Epoch 9/100
44000/44000 [==============================] - 3s 63us/sample - loss: 0.0104 - accuracy:

44000/44000 [==============================] - 3s 64us/sample - loss: 0.0016 - accuracy: 0.9995 - val_loss: 0.0969 - val_accuracy: 0.9842
Epoch 14/100
44000/44000 [==============================] - 3s 64us/sample - loss: 0.0014 - accuracy: 0.9997 - val_loss: 0.0929 - val_accuracy: 0.9844
Epoch 15/100
44000/44000 [==============================] - 3s 65us/sample - loss: 2.3315e-04 - accuracy: 1.0000 - val_loss: 0.0933 - val_accuracy: 0.9844
Epoch 16/100
44000/44000 [==============================] - 3s 65us/sample - loss: 1.3771e-04 - accuracy: 1.0000 - val_loss: 0.0946 - val_accuracy: 0.9844
Epoch 17/100
44000/44000 [==============================] - 3s 64us/sample - loss: 1.1179e-04 - accuracy: 1.0000 - val_loss: 0.0958 - val_accuracy: 0.9844
Epoch 18/100
44000/44000 [==============================] - 3s 64us/sample - loss: 9.5805e-05 - accuracy: 1.0000 - val_loss: 0.0971 - val_accuracy: 0.9844
Epoch 19/100
44000/44000 [==============================] - 3s 66us/sample - loss: 8.5413e-

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed: 55.3min finished


Train on 55000 samples, validate on 5000 samples
Epoch 1/100
55000/55000 [==============================] - 4s 79us/sample - loss: 0.2409 - accuracy: 0.9278 - val_loss: 0.1112 - val_accuracy: 0.9664
Epoch 2/100
55000/55000 [==============================] - 4s 66us/sample - loss: 0.0984 - accuracy: 0.9698 - val_loss: 0.0861 - val_accuracy: 0.9746
Epoch 3/100
55000/55000 [==============================] - 4s 67us/sample - loss: 0.0666 - accuracy: 0.9797 - val_loss: 0.0731 - val_accuracy: 0.9774
Epoch 4/100
55000/55000 [==============================] - 4s 65us/sample - loss: 0.0480 - accuracy: 0.9848 - val_loss: 0.0746 - val_accuracy: 0.9790
Epoch 5/100
55000/55000 [==============================] - 4s 65us/sample - loss: 0.0333 - accuracy: 0.9898 - val_loss: 0.0741 - val_accuracy: 0.9762
Epoch 6/100
55000/55000 [==============================] - 4s 65us/sample - loss: 0.0264 - accuracy: 0.9916 - val_loss: 0.0777 - val_accuracy: 0.9776
Epoch 7/100
55000/55000 [==========================

## Select The Best Model

Using the optimal hyperparameter values, create the best model.

In [6]:
model = mlp_cv.best_estimator_.model

## Evaluate the Optimal Model

In [7]:
train_loss = model.evaluate(X_train, y_train, verbose=0)[0]
train_accuracy = model.evaluate(X_train, y_train, verbose=0)[1]

test_loss = model.evaluate(X_test, y_test, verbose=0)[0]
test_accuracy = model.evaluate(X_test, y_test, verbose=0)[1]

print("Constant Learning Rate - Train Accuracy: ", train_accuracy)
print("Constant Learning Rate - Test Accuracy: ", test_accuracy)

print("\nConstant Learning Rate - Train Loss: ", train_loss)
print("Constant Learning Rate - Test Loss: ", test_loss)

# model.predict(X_test) method return 10 probabilities per class for each instance (Dimension Nx10)
y_test_predicted = model.predict(X_test)
y_test_predicted = np.argmax(y_test_predicted, axis=1) # get the label/index of the highest probability class

# model.predict_classes(X_test) method returns the index (class label) with largest probability (1D array)
#y_test_predicted= model.predict_classes(X_test)


y_train_predicted = model.predict(X_train)
y_train_predicted = np.argmax(y_train_predicted, axis=1) # get the label/index of the highest probability class


print("\nTest Confusion Matrix:")
print(confusion_matrix(y_test, y_test_predicted))

print("\nClassification Report:")
print(classification_report(y_test, y_test_predicted))

Constant Learning Rate - Train Accuracy:  0.99716365
Constant Learning Rate - Test Accuracy:  0.9806

Constant Learning Rate - Train Loss:  0.011166327119051394
Constant Learning Rate - Test Loss:  0.06529028431936458

Test Confusion Matrix:
[[ 973    1    1    0    1    0    2    1    1    0]
 [   0 1125    3    1    0    0    2    1    3    0]
 [   5    1 1010    5    2    0    2    3    3    1]
 [   0    0    5  995    0    2    0    2    3    3]
 [   1    0    3    1  961    0    1    1    0   14]
 [   2    0    0   14    1  870    2    0    1    2]
 [   4    4    1    1    3    2  941    1    1    0]
 [   1    6    6    2    1    0    1 1003    2    6]
 [   4    1    4    9    2    1    1    3  945    4]
 [   2    2    0    5   11    2    0    3    1  983]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0